/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-10-01 07:34:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web.page.emp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class editEmp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>My JSP'EditEmp.jsp' starting page</title>\r\n");
      out.write("\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody {background-color: #FFFFFF}\r\n");
      out.write("\t.button{\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground-image: url(web/imgs/button_normal.jpg);\r\n");
      out.write("\twidth: 102px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tborder: 0px solid #fff;\r\n");
      out.write("\tline-height: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#addemp,#emplist{margin-left: auto;margin-right: auto;width: 550px;}\r\n");
      out.write("#addemp ul{\r\n");
      out.write("\tclear: left;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("#addemp ul li{list-style: none;text-align: left;float: left; margin-left:0px;margin-top: 5px;}\r\n");
      out.write("#addemp label {float: left;display: block;width: 80px;margin: 0px;text-align: right;border: #333 0px solid; font-size: 12px;color: #3443ad;}\r\n");
      out.write("#addemp input{border: #A4B97E 1px solid;margin: 0px;}\r\n");
      out.write("#addemp sytle_box{border-width: 0px;height: 18px;}\r\n");
      out.write("#addemp input_r{background-color: #f1f1f1;}\r\n");
      out.write("\r\n");
      out.write("legend {font-size: 12px;}\r\n");
      out.write("form {display: inline;padding: 0px;margin: 0px;}\r\n");
      out.write(".button{\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground-image: url(web/imgs/button_normal.jpg);\r\n");
      out.write("\twidth: 102px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tborder: 0px solid #fff;\r\n");
      out.write("\tline-height: 35px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction buttonNormal(obj) {\r\n");
      out.write("\t\tobj.style.backgroundImage=\"url('web/imgs/button_normal.jpg')\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction buttonHover(obj) {\r\n");
      out.write("\t\tobj.style.backgroundImage=\"url('web/imgs/button_hover.jpg')\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"addemp\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t<legend>编辑员工信息</legend>\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"\" id=\"form1\" name=\"form1\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><label>账&nbsp;&nbsp;号：</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"loginName\" value=\"\" readonly=\"readonly\" disabled=\"disabled\" class=\"input_r\"></li>\r\n");
      out.write("\t\t\t\t\t<li lass=\"left\"><label>密&nbsp;&nbsp;码:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"loginPwd\" value=\"\" readonly=\"readonly\" disabled=\"disabled\"  class=\"unput_r\"></li>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><label>员工编号：</label><input type=\"text\" name=\"empNo\" value=\"\"></li>\r\n");
      out.write("\t\t\t\t\t<li><label>员工姓名:</label><input type=\"text\" name=\"empName\" value=\"\"></li>\r\n");
      out.write("\t\t\t\t\t<li><label>所属部门：</label><input type=\"text\" name=\"deptName\" value=\"\"></li>\r\n");
      out.write("\t\t\t\t\t<li><label>性别:</label><input type=\"text\" name=\"sex\" value=\"\"></li>\r\n");
      out.write("\t\t\t\t\t<li><label>所任职务:</label><input type=\"text\" name=\"job\" value=\"\"></li>\r\n");
      out.write("\t\t\t\t\t<li><label>联系电话:</label><input type=\"text\" name=\"phone\" value=\"\"></li>\r\n");
      out.write("\t\t\t\t\t<li><label>现所在住址:</label><input type=\"text\" name=\"address\" value=\"\" maxlength=\"120\"  style=\"width: 400px;\"></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"width: 100%;text-align: center;\"><input type=\"submit\" name=\"cmdSave\" value=\"修改\" onmouseout=\"buttonNormal(this)\"\r\n");
      out.write("\t\t\t\t\t\tonmouseover=\"buttonHover(this)\" class=\"button\" style=\"border: 0px solid #fff;\" onclick=\"alert('修改成功');return false;\"></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
