/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-10-13 16:06:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web.page.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class main_005fright_005fqxgl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'main_right_qxgl.jsp' starting page</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"web/css/reset.css\" />\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t.iconButton{\r\n");
      out.write("\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\twidth:60px;\r\n");
      out.write("\t\t\theight:72px\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.iconImage{\r\n");
      out.write("\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\twidth:60px;\r\n");
      out.write("\t\t\theight:60px\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"web/js/mainjs.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <div style=\" width:100%; height:29px;\">\r\n");
      out.write("\t\t<table cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t<tr height=\"29\">\r\n");
      out.write("\t\t\t\t<td width=\"14px\" height=\"29px\"><div style=\"background-image:url(web/imgs/Bitmap_203.bmp); width:14px; height:29px;line-height:29px;\"></div></td>\r\n");
      out.write("\t\t\t\t<td width=\"60%\"><div style=\"background-image:url(web/imgs/Bitmap_202.bmp); width:100%; height:29px;float:left; line-height:29px\">\r\n");
      out.write("\t\t\t\t<b style=\"color:#0066ff\">业务处理</b></div></td>\r\n");
      out.write("\t\t\t\t<td width=\"2px\"><div style=\"background-image:url(web/imgs/Bitmap_201.bmp); width:2px; height:29px\"></div></td>\r\n");
      out.write("\t\t\t\t<td width=\"40%\"><div style=\"background-image:url(web/imgs/Bitmap_202.bmp); width:100%; height:29px;float:left; line-height:29px\">\r\n");
      out.write("\t\t\t\t<b style=\"color:#0066ff\">&nbsp;&nbsp;业务介绍</b></div></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"800\">\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<!-- 左边操作部分 -->\r\n");
      out.write("\t\t\t\t<td style=\"border-right:1px dashed #aaaaaa\">\r\n");
      out.write("\t\t\t\t\t<!-- 模块管理 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"iconButton\" style=\"position:absolute;left:80px; top:100px\">\r\n");
      out.write("\t\t\t\t\t <div class=\"iconImage\" \r\n");
      out.write("\t\t\t\t\t\t style=\"background-image:url(web/imgs/icos/mkgl.jpg);\" \r\n");
      out.write("\t\t\t\t\t\t onclick=\"openModalWindow('bfmod/mod.action',615,420,'mod')\">\r\n");
      out.write("\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t <div style=\"text-align:center; line-height:20px\" onclick=\"openModalWindow('bfmod/mod.action',615,420,'mod')\">模块管理</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 账号管理 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"iconButton\" style=\"position:absolute;left:280px; top:100px\">\r\n");
      out.write("\t\t\t\t\t <div class=\"iconImage\" \r\n");
      out.write("\t\t\t\t\t\t style=\"background-image:url(web/imgs/icos/zhgl.jpg);\" \r\n");
      out.write("\t\t\t\t\t\t onclick=\"openModalWindow('../purview/account/account.html',615,550)\">\r\n");
      out.write("\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t <div style=\"text-align:center; line-height:20px\" onclick=\"openModalWindow('../purview/account/account.html',615,550)\">账号管理</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<!-- 右边功能介绍部分 -->\r\n");
      out.write("\t\t\t\t<td>asdfasdf</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
